web:
  build: .
  # image: exercise2railsappwithdockercompose_web
  links:
    - postgres
  ports:
    - 3000:3000
postgres:
  image: postgres:alpine
  environment:
    POSTGRES_USER: rails_app
    POSTGRES_PASSWORD: postgres_pass
  container_name: postgres